<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <PackageId>RazQL.Core</PackageId>
    <RootNamespace>RazQL</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="RazorEngineCore" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="RazQL.Tests" />
    <None Update="README.md" Pack="true" PackagePath="/" />
  </ItemGroup>

</Project>
