<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>RazQL.Dapper</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../RazQL/RazQL.csproj" />
    <None Update="README.md" Pack="true" PackagePath="/" />
  </ItemGroup>

</Project>
