<Project>

  <Target Name="_PrepareRazQLTemplateSourceGenerator"
          BeforeTargets="GenerateMSBuildEditorConfigFileShouldRun"
          DependsOnTargets="AssignTargetPaths">
    <ItemGroup>
      <CompilerVisibleItemMetadata Include="AdditionalFiles"
                                   MetadataName="RazQLTemplateItemType" />
      <CompilerVisibleItemMetadata Include="AdditionalFiles"
                                   MetadataName="CopyToOutputDirectory" />
      <CompilerVisibleItemMetadata Include="AdditionalFiles"
                                   MetadataName="TargetPath" />
      <CompilerVisibleItemMetadata Include="AdditionalFiles"
                                   MetadataName="RazQLManifestResourceName" />

      <EmbeddedResource Update="@(EmbeddedResource)"
                        Condition="'%(EmbeddedResource.Extension)' == '.cshtml' and $([System.String]::Copy('%(EmbeddedResource.Filename)').EndsWith('.sql')) and '%(EmbeddedResource.LogicalName)' == ''">
        <LogicalName Condition="'$(RootNamespace)' != ''">$(RootNamespace).$([System.String]::Copy('%(EmbeddedResource.TargetPath)').Replace('\', '.').Replace('/', '.'))</LogicalName>
        <LogicalName Condition="'$(RootNamespace)' == ''">$([System.String]::Copy('%(EmbeddedResource.TargetPath)').Replace('\', '.').Replace('/', '.'))</LogicalName>
      </EmbeddedResource>

      <_RazQLEmbeddedTemplate Include="@(EmbeddedResource)"
                              Condition="'%(EmbeddedResource.Extension)' == '.cshtml' and $([System.String]::Copy('%(EmbeddedResource.Filename)').EndsWith('.sql'))" />
      <_RazQLContentTemplate Include="@(ContentWithTargetPath)"
                            Condition="'%(ContentWithTargetPath.Extension)' == '.cshtml' and $([System.String]::Copy('%(ContentWithTargetPath.Filename)').EndsWith('.sql'))" />

      <AdditionalFiles Include="@(_RazQLEmbeddedTemplate)"
                       RazQLTemplateItemType="EmbeddedResource"
                       RazQLManifestResourceName="%(_RazQLEmbeddedTemplate.LogicalName)" />
      <AdditionalFiles Include="@(_RazQLContentTemplate)"
                       RazQLTemplateItemType="Content" />
    </ItemGroup>
  </Target>

</Project>
