using System.Globalization;
using System.Text;
using Microsoft.CodeAnalysis;
using RazQL.Generators.Models;

namespace RazQL.Generators.Emission;

internal static class GeneratedMapperEmitter
{
    private static readonly SymbolDisplayFormat TypeDisplayFormat =
        SymbolDisplayFormat.FullyQualifiedFormat.WithMiscellaneousOptions(
            SymbolDisplayFormat.FullyQualifiedFormat.MiscellaneousOptions |
            SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier |
            SymbolDisplayMiscellaneousOptions.EscapeKeywordIdentifiers);

    public static string GetHintName(MapperModel mapper)
    {
        return $"RazQL.Mapper.{GetMapperIdentifier(mapper)}.g.cs";
    }

    public static string Emit(MapperModel mapper)
    {
        var className = $"RazQLMapper_{GetMapperIdentifier(mapper)}";
        var generatedNamespace = GetGeneratedNamespace(mapper);
        var methods = mapper.Methods
            .OrderBy(
                static method => method.Method.ToDisplayString(SymbolDisplayFormat.CSharpErrorMessageFormat),
                StringComparer.Ordinal)
            .ToArray();

        var source = new StringBuilder()
            .AppendLine("// <auto-generated />")
            .AppendLine("#nullable enable")
            .AppendLine("#pragma warning disable CS8619")
            .AppendLine()
            .AppendLine("[assembly: global::RazQL.RazQLMapperImplementationAttribute(")
            .Append("    typeof(")
            .Append(DisplayType(mapper.MapperInterface))
            .AppendLine("),")
            .Append("    typeof(global::")
            .Append(generatedNamespace)
            .Append('.')
            .Append(className)
            .AppendLine("))]")
            .AppendLine()
            .Append("namespace ")
            .Append(generatedNamespace)
            .AppendLine(";")
            .AppendLine()
            .Append("internal sealed class ")
            .Append(className)
            .Append(" : ")
            .Append(DisplayType(mapper.MapperInterface))
            .Append(", global::RazQL.IMapperTemplatePreloader")
            .AppendLine()
            .AppendLine("{")
            .AppendLine("    private readonly global::RazQL.Execution.IQueryExecutor _executor;")
            .AppendLine();

        for (var index = 0; index < methods.Length; index++)
        {
            AppendQueryDescriptor(source, mapper, methods[index], index);
        }

        source.Append("    public ")
            .Append(className)
            .AppendLine("(global::RazQL.Execution.IQueryExecutor executor)")
            .AppendLine("    {")
            .AppendLine("        _executor = executor;")
            .AppendLine("    }");

        for (var index = 0; index < methods.Length; index++)
        {
            source.AppendLine();
            AppendMethod(source, methods[index], index);
        }

        source.AppendLine();
        AppendTemplatePreloader(source, methods);

        return source.AppendLine("}")
            .ToString();
    }

    private static void AppendQueryDescriptor(
        StringBuilder source,
        MapperModel mapper,
        MapperMethodModel method,
        int index)
    {
        source.Append("    private static readonly global::RazQL.Template.QueryDescriptor QueryDescriptor_")
            .Append(index.ToString("D3", CultureInfo.InvariantCulture))
            .AppendLine(" =")
            .Append("        global::RazQL.Template.QueryDescriptor.ForExpression<")
            .Append(DisplayType(mapper.MapperInterface))
            .Append(", ")
            .Append(DisplayType(method.CriteriaType!))
            .Append(", ")
            .Append(DisplayType(method.ResultType!))
            .Append(">(mapper => mapper.")
            .Append(EscapeIdentifier(method.Method.Name))
            .AppendLine(");")
            .AppendLine();
    }

    private static void AppendTemplatePreloader(
        StringBuilder source,
        IReadOnlyList<MapperMethodModel> methods)
    {
        source.AppendLine("    global::System.Collections.Generic.IEnumerable<global::System.Threading.Tasks.Task>")
            .AppendLine("        global::RazQL.IMapperTemplatePreloader.PreloadTemplates(")
            .AppendLine("            global::RazQL.Template.ITemplateCache templateCache,")
            .AppendLine("            global::System.Threading.CancellationToken cancellationToken)")
            .AppendLine("    {")
            .AppendLine("        global::System.ArgumentNullException.ThrowIfNull(templateCache);")
            .AppendLine()
            .AppendLine("        return new global::System.Threading.Tasks.Task[]")
            .AppendLine("        {");

        for (var index = 0; index < methods.Count; index++)
        {
            source.Append("            templateCache.GetTemplateAsync<")
                .Append(DisplayType(methods[index].CriteriaType!))
                .AppendLine(">(")
                .Append("                QueryDescriptor_")
                .Append(index.ToString("D3", CultureInfo.InvariantCulture))
                .AppendLine(",")
                .AppendLine("                cancellationToken),");
        }

        source.AppendLine("        };")
            .AppendLine("    }");
    }

    private static void AppendMethod(
        StringBuilder source,
        MapperMethodModel method,
        int index)
    {
        var criteriaParameter = method.Method.Parameters[0];
        var cancellationTokenParameter = method.Method.Parameters[1];

        source.Append("    public ")
            .Append(DisplayType(method.Method.ReturnType))
            .Append(' ')
            .Append(EscapeIdentifier(method.Method.Name))
            .Append('(')
            .Append(DisplayType(criteriaParameter.Type))
            .Append(' ')
            .Append(EscapeIdentifier(criteriaParameter.Name))
            .Append(", ")
            .Append(DisplayType(cancellationTokenParameter.Type))
            .Append(' ')
            .Append(EscapeIdentifier(cancellationTokenParameter.Name))
            .AppendLine(") =>")
            .Append("        _executor.")
            .Append(method.ResultShape == MapperMethodModel.QueryResultShape.Many
                ? "ExecuteAsync"
                : "ExecuteSingleOrDefaultAsync")
            .Append('<')
            .Append(DisplayType(method.CriteriaType!))
            .Append(", ")
            .Append(DisplayType(method.ResultType!))
            .AppendLine(">(")
            .Append("            QueryDescriptor_")
            .Append(index.ToString("D3", CultureInfo.InvariantCulture))
            .AppendLine(",")
            .Append("            ")
            .Append(EscapeIdentifier(criteriaParameter.Name))
            .AppendLine(",")
            .Append("            ")
            .Append(EscapeIdentifier(cancellationTokenParameter.Name))
            .AppendLine(");");
    }

    private static string GetMapperIdentifier(MapperModel mapper)
    {
        var typeName = mapper.MapperInterface.Name;
        var sanitizedName = new string(typeName
            .Select(static character => char.IsLetterOrDigit(character) ? character : '_')
            .ToArray());
        var qualifiedName = mapper.MapperInterface.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        return $"{sanitizedName}_{ComputeHash(qualifiedName):x8}";
    }

    private static string GetGeneratedNamespace(MapperModel mapper)
    {
        return mapper.MapperInterface.ContainingNamespace.IsGlobalNamespace
            ? "RazQL.Generated"
            : $"{mapper.MapperInterface.ContainingNamespace.ToDisplayString()}.Generated";
    }

    private static uint ComputeHash(string value)
    {
        const uint offsetBasis = 2166136261;
        const uint prime = 16777619;
        var hash = offsetBasis;

        unchecked
        {
            foreach (var character in value)
            {
                hash ^= character;
                hash *= prime;
            }
        }

        return hash;
    }

    private static string DisplayType(ITypeSymbol type)
    {
        return type.ToDisplayString(TypeDisplayFormat);
    }

    private static string EscapeIdentifier(string identifier)
    {
        return $"@{identifier}";
    }
}
